package com.strod.moduleinit.compiler;

public class ModuleInitConsts {
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY APT.";
    public static final String SEPARATOR = "$$";
    public static final String PROJECT = "ModuleInit";
    public static final String ROOT = "Root";
    public static final String GROUP = "Group";


    private static final String MODULEINIT_PACKAGE = "com.strod.moduleinit.api";
    public static final String MODULEINIT_ROOT = MODULEINIT_PACKAGE  + ".core.ModuleInitRoot";
    public static final String MODULEINIT_GROUP = MODULEINIT_PACKAGE  + ".core.ModuleInitGroup";



    public static final String METHOD_LOAD_INTO = "loadInto";
    public static final String PACKAGE_OF_GENERATE_FILE = "com.strod.moduleinit";
    public static final String NAME_OF_INTERCEPTOR = PROJECT + SEPARATOR + "Groups";

    public static final String DOT = ".";
    public static final String MODULEINIT_SP_CACHE_KEY = "SP_MODULEINIT_CACHE";
    public static final String MODULEINIT_SP_KEY_MAP = "MODULEINIT_MAP";

    // Annotation type
    public static final String ANNOTATION_TYPE_INTECEPTOR = MODULEINIT_PACKAGE  + ".ModuleInit";

}
